#!/usr/bin/env python
# -*- coding:utf-8 -*-


# ############################################################################
#  license :
# ============================================================================
#
#  File :        Motor.py
#
#  Project :     
#
# This file is part of Tango device class.
# 
# Tango is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# Tango is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with Tango.  If not, see <http://www.gnu.org/licenses/>.
# 
#
#  $Author :      d.dosa95$
#
#  $Revision :    $
#
#  $Date :        $
#
#  $HeadUrl :     $
# ============================================================================
#            This file is generated by POGO
#     (Program Obviously used to Generate tango Object)
# ############################################################################

__all__ = ["Motor", "MotorClass", "main"]

__docformat__ = 'restructuredtext'

import PyTango
import sys
# Add additional import
#----- PROTECTED REGION ID(Motor.additionnal_import) ENABLED START -----#

#----- PROTECTED REGION END -----#	//	Motor.additionnal_import

# Device States Description
# ON : 
# OFF : 


class Motor (PyTango.Device_4Impl):
    """"""
    
    # -------- Add you global variables here --------------------------
    #----- PROTECTED REGION ID(Motor.global_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	Motor.global_variables

    def __init__(self, cl, name):
        PyTango.Device_4Impl.__init__(self,cl,name)
        self.debug_stream("In __init__()")
        Motor.init_device(self)
        #----- PROTECTED REGION ID(Motor.__init__) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.__init__
        
    def delete_device(self):
        self.debug_stream("In delete_device()")
        #----- PROTECTED REGION ID(Motor.delete_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.delete_device

    def init_device(self):
        self.debug_stream("In init_device()")
        self.get_device_properties(self.get_device_class())
        self.attr_Speed_read = 0.0
        #----- PROTECTED REGION ID(Motor.init_device) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.init_device

    def always_executed_hook(self):
        self.debug_stream("In always_excuted_hook()")
        #----- PROTECTED REGION ID(Motor.always_executed_hook) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.always_executed_hook

    # -------------------------------------------------------------------------
    #    Motor read/write attribute methods
    # -------------------------------------------------------------------------
    
    def read_Speed(self, attr):
        self.debug_stream("In read_Speed()")
        #----- PROTECTED REGION ID(Motor.Speed_read) ENABLED START -----#
        attr.set_value(self.attr_Speed_read)
        
        #----- PROTECTED REGION END -----#	//	Motor.Speed_read
        
    def write_Speed(self, attr):
        self.debug_stream("In write_Speed()")
        data = attr.get_write_value()
        #----- PROTECTED REGION ID(Motor.Speed_write) ENABLED START -----#
        self.attr_Writableizmize = data
        #----- PROTECTED REGION END -----#	//	Motor.Speed_write
        
    def is_Speed_allowed(self, attr):
        self.debug_stream("In is_Speed_allowed()")
        if attr==PyTango.AttReqType.READ_REQ:
            state_ok = not(self.get_state() in [PyTango.DevState.OFF])
        else:
            state_ok = not(self.get_state() in [PyTango.DevState.OFF])
        #----- PROTECTED REGION ID(Motor.is_Speed_allowed) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.is_Speed_allowed
        return state_ok
        
    
    
            
    def read_attr_hardware(self, data):
        self.debug_stream("In read_attr_hardware()")
        #----- PROTECTED REGION ID(Motor.read_attr_hardware) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.read_attr_hardware


    # -------------------------------------------------------------------------
    #    Motor command methods
    # -------------------------------------------------------------------------
    
    def On(self):
        """ 
        """
        self.debug_stream("In On()")
        #----- PROTECTED REGION ID(Motor.On) ENABLED START -----#
        self.set_state(PyTango.DevState.ON)
        self.set_status("The motor is ON")
        #----- PROTECTED REGION END -----#	//	Motor.On
        
    def is_On_allowed(self):
        self.debug_stream("In is_On_allowed()")
        state_ok = not(self.get_state() in [PyTango.DevState.ON])
        #----- PROTECTED REGION ID(Motor.is_On_allowed) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.is_On_allowed
        return state_ok
        
    def Off(self):
        """ 
        """
        self.debug_stream("In Off()")
        #----- PROTECTED REGION ID(Motor.Off) ENABLED START -----#
        self.set_state(PyTango.DevState.OFF)
        self.set_status("The motor is OFF")
        #----- PROTECTED REGION END -----#	//	Motor.Off
        
    def is_Off_allowed(self):
        self.debug_stream("In is_Off_allowed()")
        state_ok = not(self.get_state() in [PyTango.DevState.OFF])
        #----- PROTECTED REGION ID(Motor.is_Off_allowed) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.is_Off_allowed
        return state_ok
        
    def SetSpeed(self, argin):
        """ 
        :param argin: 
        :type argin: PyTango.DevDouble
        """
        self.debug_stream("In SetSpeed()")
        #----- PROTECTED REGION ID(Motor.SetSpeed) ENABLED START -----#
        self.attr_Speed_read = argin
        #----- PROTECTED REGION END -----#	//	Motor.SetSpeed
        

    #----- PROTECTED REGION ID(Motor.programmer_methods) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	Motor.programmer_methods

class MotorClass(PyTango.DeviceClass):
    # -------- Add you global class variables here --------------------------
    #----- PROTECTED REGION ID(Motor.global_class_variables) ENABLED START -----#
    
    #----- PROTECTED REGION END -----#	//	Motor.global_class_variables


    #    Class Properties
    class_property_list = {
        }


    #    Device Properties
    device_property_list = {
        }


    #    Command definitions
    cmd_list = {
        'On':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'Off':
            [[PyTango.DevVoid, "none"],
            [PyTango.DevVoid, "none"]],
        'SetSpeed':
            [[PyTango.DevDouble, "none"],
            [PyTango.DevVoid, "none"]],
        }


    #    Attribute definitions
    attr_list = {
        'Speed':
            [[PyTango.DevDouble,
            PyTango.SCALAR,
            PyTango.READ_WRITE]],
        }


def main():
    try:
        py = PyTango.Util(sys.argv)
        py.add_class(MotorClass, Motor, 'Motor')
        #----- PROTECTED REGION ID(Motor.add_classes) ENABLED START -----#
        
        #----- PROTECTED REGION END -----#	//	Motor.add_classes

        U = PyTango.Util.instance()
        U.server_init()
        U.server_run()

    except PyTango.DevFailed as e:
        print ('-------> Received a DevFailed exception:', e)
    except Exception as e:
        print ('-------> An unforeseen exception occured....', e)

if __name__ == '__main__':
    main()
